### ISSUE TITLE
Public Beta Checklist

### ISSUE THREAD

**Issue by emplums** [primer/components#123]
Items that need to be completed before our first public beta

### Must
- [x] Support documentation for components in markdown format
- [x] Point site to primer.style/components
- [x] Default theme for each component?
- [x] "Good enough" test coverage
- [x] Index page design
- [x] Every component documented
  - [x] Simple (default) example
  - [x] Component Props
  - [x] Basic implementation guidelines
- [x] System props documented
- [x] Installation guidelines, aka "how to use in your app"
  - confirm what packages are needed
- [x] Component(s) to import Primer CSS #124 
- [x] Rename the repo to `primer/components`
- [x] Scope on npm

#### Dependency
- [x] Shipped primer.style

### Should
- [x] Improved doc design https://github.com/primer/primer-react/issues/231
- [ ] A way to provide feedback

### Could
- [x] Copy over usage guidelines from style guide
- [x] Add favicon

### Won't
- Remaining Primer CSS components #100 
- Provide docs for how to use your own theme
- Ship dev mode
