### ISSUE TITLE
[Epic] TypeScript refactor

### ISSUE THREAD

**Issue by colebemis** [primer/components#970]
## Objective

Rewrite Primer React components in TypeScript.

📄  [TypeScript ADR](https://github.com/primer/components/blob/main/contributor-docs/adrs/adr-001-typescript.md)
📄 [TypeScript notes google doc](https://docs.google.com/document/d/13U7oryeaPSLWlJxw6y1HPaSnrJ_SwhFiR9SG9JlYYfQ/edit)

## Team
- DRI: @colebemis
- Engineering: @colebemis @smockle @bscofield @VanAnderson 
- Product: n/a
- Design: n/a

### Phase 1: Setup
- [x] Support `.ts` and `.tsx` files https://github.com/primer/components/pull/959
- [x] Type check test files https://github.com/primer/components/pull/971
### Phase 2: Migrate
- [x] Migrate components¹

**In Review or Done**
- [x] Dialog @VanAnderson https://github.com/primer/components/pull/1060
- [x] Dropdown @colebemis https://github.com/primer/components/pull/1059
- [x] theme @colebemis https://github.com/primer/components/pull/1058
- [x] utils @VanAnderson https://github.com/primer/components/pull/1055
- [x] SelectMenu @colebemis https://github.com/primer/components/pull/1048
- [x] Pagination @VanAnderson https://github.com/primer/components/pull/1047
- [x] PointerBox @colebemis https://github.com/primer/components/pull/1042
- [x] SideNav @VanAnderson https://github.com/primer/components/pull/1040
- [x] SubNav @VanAnderson https://github.com/primer/components/pull/1038
- [x] Timeline @colebemis https://github.com/primer/components/pull/1037
- [x] CircleOcticon @colebemis https://github.com/primer/components/pull/1036
- [x] CircleBadge @colebemis https://github.com/primer/components/pull/1035
- [x] Popover @colebemis https://github.com/primer/components/pull/1034
- [x] Tooltip @colebemis https://github.com/primer/components/pull/1033
- [x] AvatarStack @colebemis https://github.com/primer/components/pull/1032
- [x] TabNav @VanAnderson  https://github.com/primer/components/pull/1029
- [x] AvatarPair @colebemis https://github.com/primer/components/pull/1031
- [x] Caret @colebemis https://github.com/primer/components/pull/1030
- [x] TextInput @colebemis https://github.com/primer/components/pull/1028
- [x] Details @VanAnderson https://github.com/primer/components/pull/1026
- [x] Button @smockle https://github.com/primer/components/pull/1017
- [x] Header @VanAnderson https://github.com/primer/components/pull/1020
- [x] FilterList @colebemis https://github.com/primer/components/pull/1015
- [x] UnderlineNav @colebemis https://github.com/primer/components/pull/1014
- [x] Breadcrumb @colebemis https://github.com/primer/components/pull/1012
- [x] Link @VanAnderson https://github.com/primer/components/pull/1011
- [x] StateLabel @colebemis https://github.com/primer/components/pull/1008
- [x] FilteredSearch @colebemis https://github.com/primer/components/pull/1006
- [x] CounterLabel @colebemis https://github.com/primer/components/pull/1005
- [x] Truncate @colebemis https://github.com/primer/components/pull/1003
- [x] FormGroup @colebemis https://github.com/primer/components/pull/999
- [x] Position @colebemis https://github.com/primer/components/pull/998
- [x] Flash @colebemis https://github.com/primer/components/pull/995
- [x] StyledOcticon @colebemis https://github.com/primer/components/pull/993
- [x] ProgressBar @colebemis https://github.com/primer/components/pull/987
- [x] Avatar @bscofield https://github.com/primer/components/pull/984
- [x] Grid @colebemis https://github.com/primer/components/pull/989
- [x] Flex @colebemis https://github.com/primer/components/pull/986
- [x] BorderBox #973
- [x] Text #979
- [x] BaseStyles #982
- [x] Box #959
- [x] BranchName #974
- [x] Heading #975
- [x] Label #976
- [x] LabelGroup #976
- [x] Pagehead #977

### Phase 3: Clean up
- [x] Remove ambient declaration file (`index.d.ts`) https://github.com/primer/components/pull/1147
- [x] Remove propTypes https://github.com/primer/components/pull/1068

### Postponed
- Update [contributor guidelines](https://github.com/primer/components/blob/main/CONTRIBUTING.md)
- Remove default exports
- Generate prop documentation https://github.com/primer/components/issues/1109

## ¹How to migrate a component to TypeScript
The migration process for each component may vary, but it will likely follow these high-level steps:

#### 1. Change the file extension from `.js` to `.tsx`

```
src/Box.js → src/Box.tsx
```

#### 2. Add type annotations to the component file

Here are type annotations for the `Box` component:
   
   ```diff
     // src/Box.tsx
     import styled from 'styled-components'
   + import {COMMON, FLEX, LAYOUT, SystemCommonProps, SystemFlexProps, LayoutProps} from './constants'
   + import sx, {SxProp} from './sx'
   + import {ComponentProps} from './utils/types'


   + const Box = styled.div<CommonProps & FlexProps & LayoutProps & SxProp>`
       ${COMMON}
       ${FLEX}
       ${LAYOUT}
       ${sx}
     `
   + export type BoxProps = ComponentProps<typeof Box>
     export default Box
   ```

Most Primer React components will follow a similar pattern. Each component should export a `___Props` type in addition to the default export.

#### 3. Change the file extension of tests

```
src/__tests__/Box.js → src/__tests__/Box.tsx
```

👉 See the [TypeScript notes google doc](https://docs.google.com/document/d/13U7oryeaPSLWlJxw6y1HPaSnrJ_SwhFiR9SG9JlYYfQ/edit#) for more information on TypeScript migration.

## Exit criteria

- [x] All JavaScript files in the `src` directory of [primer/components](https://github.com/primer/components) have been rewritten in TypeScript

/cc @philipbremer

**Comment by colebemis** [comment]
### Status

💚 Green

### Ships

n/a

### Blockers

We’re getting `as` prop-related errors when testing the generated type definitions in Memex which is blocking us from merging https://github.com/primer/components/pull/1067

### Up Next

- I'll be meeting with @T-Hugs next week to discuss the `as` prop errors and brainstorm possible workarounds.
- I'll be adding TypeScript guidelines to the [contribution guidelines](https://github.com/primer/components/blob/main/contributor-docs/CONTRIBUTING.md)

**Comment by colebemis** [comment]
### Status

💛  Yellow

### Blockers

The final step of this TypeScript refactor is to replace our manually maintained type definitions with type definitions generated by TypeScript. However, after testing in Memex, I found that the generated type definitions were causing errors because of the way the `as` prop is defined. 

I figured out a way to correctly define types for the `as` prop but it will require us to update all our components:  

<details>
  <summary><strong> Here's an example of how our components will need to be updated</strong></summary>

```diff
import styled from 'styled-components'
import {COMMON, FLEX, LAYOUT, SystemCommonProps, SystemFlexProps, SystemLayoutProps} from './constants'
import sx, {SxProp} from './sx'
- import {ComponentProps} from './utils/types'
+ import {ForwardRefComponent} from './utils/polymorphic'

+ const defaultElement = 'div'

+ export type BoxProps = SystemCommonProps &
+  SystemFlexProps &
+  SystemLayoutProps &
+  SxProp

+ type BoxComponent = ForwardRefComponent<typeof defaultElement, BoxProps>

+ const Box = styled(defaultElement)<BoxProps>`
- const Box = styled.div<BoxProps>`
  ${COMMON}
  ${FLEX}
  ${LAYOUT}
  ${sx};
+ ` as BoxComponent
- `

- export type BoxProps = ComponentProps<typeof Box>
export default Box
```

</details>

I haven't had time to completely implement this solution because of [Primer React theming](https://github.com/github/design-systems/issues/1219) work. I'll reach out to @VanAnderson to see if he as the bandwidth to take this on. 

### Up Next

- Fix the `as` prop types so we can replace our manually maintained type definitions with type definitions generated by TypeScript
- Add TypeScript guidelines to the [contribution guidelines](https://github.com/primer/components/blob/main/contributor-docs/CONTRIBUTING.md)

**Comment by colebemis** [comment]
### Status

💛  Yellow


No updates on TypeScript this week because @VanAnderson and I have been focused on the [Primer React theming](https://github.com/github/design-systems/issues/1219) epic.

### Up Next

- Fix the `as` prop types so we can replace our manually maintained type definitions with type definitions generated by TypeScript
- Add TypeScript guidelines to the [contribution guidelines](https://github.com/primer/components/blob/main/contributor-docs/CONTRIBUTING.md)

**Comment by colebemis** [comment]
### Status

💛  Yellow


No updates on TypeScript this week because @VanAnderson and I have been focused on the [Primer React theming](https://github.com/github/design-systems/issues/1219) epic. I'll have the bandwidth to finish up TypeScript work next week.

### Up Next

- Fix the `as` prop types so we can replace our manually maintained type definitions with type definitions generated by TypeScript
- Add TypeScript guidelines to the [contribution guidelines](https://github.com/primer/components/blob/main/contributor-docs/CONTRIBUTING.md)

**Comment by colebemis** [comment]
## 4/1 Update 

Status 💚 


### Ships

This week we replaced our hand-written type definitions with type definitions generated by the TypeScript compiler (https://github.com/primer/components/pull/1147). This means consumers get more accurate type definitions and maintainers no longer have to manually keep the type definitions in sync with the code! This is the culmination of a quarter-long effort to rewrite Primer React in TypeScript 🎉  (https://github.com/primer/components/issues/970). These changes will be included in the [next release of Primer React](https://github.com/primer/components/pull/1150).

### Up Next

- Write guidelines for authoring components in TypeScript.

**Comment by colebemis** [comment]
The exit criteria has been met 🎉  I'm going to go ahead and close this issue. We can track follow-up tasks in separate issues.
